#define ET_EXPR_ASSIGN                           1
#define ET_EXPR_AND                              2
#define ET_EXPR_OR                               3
#define ET_EXPR_NOT                              4
#define ET_EXPR_LESS                             5
#define ET_EXPR_LESS_OR_EQUAL                    6
#define ET_EXPR_GREATER                          7
#define ET_EXPR_GREATER_OR_EQUAL                 8
#define ET_EXPR_EQUAL                            9
#define ET_EXPR_NOT_EQUAL                       10
#define ET_EXPR_PLUS                            11
#define ET_EXPR_MINUS                           12
#define ET_EXPR_UMINUS                          13
#define ET_EXPR_TIMES                           14
#define ET_EXPR_DIVIDE                          15
#define ET_EXPR_MOD                             16
#define ET_EXPR_IDENTIFIER                      17
#define ET_EXPR_DOT                             18
#define ET_EXPR_INTEGER                         19
#define ET_EXPR_FLOAT                           20
#define ET_EXPR_BOOLEAN                         21
#define ET_EXPR_STRING                          22
#define ET_EXPR_LEFT_P                          23
#define ET_EXPR_RIGHT_P                         24
