#define ET_AND                             1
#define ET_OR                              2
#define ET_LESS                            3
#define ET_LESS_OR_EQUAL                   4
#define ET_GREATER                         5
#define ET_GREATER_OR_EQUAL                6
#define ET_EQUAL                           7
#define ET_NOT_EQUAL                       8
#define ET_PLUS                            9
#define ET_MINUS                          10
#define ET_TIMES                          11
#define ET_DIVIDE                         12
#define ET_MOD                            13
#define ET_NOT                            14
#define ET_SPACE                          15
#define ET_IDENTIFIER                     16
#define ET_INTEGER                        17
#define ET_FLOAT                          18
#define ET_BOOLEAN                        19
#define ET_STRING                         20
#define ET_LEFT_P                         21
#define ET_RIGHT_P                        22
