#define ET_ASSIGN                          1
#define ET_AND                             2
#define ET_OR                              3
#define ET_LESS                            4
#define ET_LESS_OR_EQUAL                   5
#define ET_GREATER                         6
#define ET_GREATER_OR_EQUAL                7
#define ET_EQUAL                           8
#define ET_NOT_EQUAL                       9
#define ET_PLUS                           10
#define ET_MINUS                          11
#define ET_TIMES                          12
#define ET_DIVIDE                         13
#define ET_MOD                            14
#define ET_NOT                            15
#define ET_SPACE                          16
#define ET_IDENTIFIER                     17
#define ET_INTEGER                        18
#define ET_FLOAT                          19
#define ET_BOOLEAN                        20
#define ET_STRING                         21
#define ET_LEFT_P                         22
#define ET_RIGHT_P                        23
