/* Generated by re2c 0.13.5 on Wed Nov  5 11:20:53 2014 */
#line 1 "scanner.re"
#include "scanner.h"

namespace scanner
{

CToken scan(const std::string& expression, size_t& offset)
{
    std::string::const_pointer marker;
    std::string::const_pointer cursor = expression.c_str() + offset;
    std::string::const_pointer p_start = expression.c_str() + offset;
    size_t start = offset;


#line 17 "scanner.cpp"
    {
        unsigned char yych;
        unsigned int yyaccept = 0;

        yych = (unsigned char)*cursor;
        switch (yych) {
        case 0x00:    goto yy35;
        case '\t':
        case ' ':    goto yy3;
        case '!':    goto yy16;
        case '"':    goto yy9;
        case '%':    goto yy26;
        case '(':    goto yy31;
        case ')':    goto yy33;
        case '*':    goto yy28;
        case '+':    goto yy20;
        case '-':    goto yy22;
        case '/':    goto yy24;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy7;
        case '<':    goto yy11;
        case '=':    goto yy15;
        case '>':    goto yy13;
        case 'A':
        case 'a':    goto yy17;
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy30;
        case 'F':
        case 'f':    goto yy6;
        case 'N':
        case 'n':    goto yy19;
        case 'O':
        case 'o':    goto yy18;
        case 'T':
        case 't':    goto yy4;
        default:    goto yy37;
        }
yy2:
#line 48 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_SPACE, expression.substr(start, cursor - p_start)); }
#line 107 "scanner.cpp"
yy3:
        yych = (unsigned char)*++cursor;
        goto yy78;
yy4:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case 'R':
        case 'r':    goto yy75;
        default:    goto yy39;
        }
yy5:
#line 72 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_IDENTIFIER, expression.substr(start, cursor - p_start)); }
#line 121 "scanner.cpp"
yy6:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'A':
        case 'a':    goto yy70;
        default:    goto yy39;
        }
yy7:
        yyaccept = 0;
        yych = (unsigned char)*(marker = ++cursor);
        switch (yych) {
        case '.':    goto yy64;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy62;
        default:    goto yy65;
        }
yy8:
#line 50 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_FLOAT, expression.substr(start, cursor - p_start)); }
#line 149 "scanner.cpp"
yy9:
        yyaccept = 1;
        yych = (unsigned char)*(marker = ++cursor);
        goto yy57;
yy10:
#line 77 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_ERROR, expression.substr(start, cursor - p_start)); }
#line 157 "scanner.cpp"
yy11:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '=':    goto yy54;
        default:    goto yy12;
        }
yy12:
#line 54 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LESS, expression.substr(start, cursor - p_start)); }
#line 167 "scanner.cpp"
yy13:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '=':    goto yy52;
        default:    goto yy14;
        }
yy14:
#line 55 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_GREATER, expression.substr(start, cursor - p_start)); }
#line 177 "scanner.cpp"
yy15:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '=':    goto yy50;
        default:    goto yy10;
        }
yy16:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '=':    goto yy48;
        default:    goto yy10;
        }
yy17:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'N':
        case 'n':    goto yy45;
        default:    goto yy39;
        }
yy18:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'R':
        case 'r':    goto yy43;
        default:    goto yy39;
        }
yy19:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'O':
        case 'o':    goto yy40;
        default:    goto yy39;
        }
yy20:
        ++cursor;
#line 65 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_PLUS, expression.substr(start, cursor - p_start)); }
#line 215 "scanner.cpp"
yy22:
        ++cursor;
#line 66 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_MINUS, expression.substr(start, cursor - p_start)); }
#line 220 "scanner.cpp"
yy24:
        ++cursor;
#line 68 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_DIVIDE, expression.substr(start, cursor - p_start)); }
#line 225 "scanner.cpp"
yy26:
        ++cursor;
#line 69 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_MOD, expression.substr(start, cursor - p_start)); }
#line 230 "scanner.cpp"
yy28:
        ++cursor;
#line 70 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_TIMES, expression.substr(start, cursor - p_start)); }
#line 235 "scanner.cpp"
yy30:
        yych = (unsigned char)*++cursor;
        goto yy39;
yy31:
        ++cursor;
#line 74 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LEFT_P, expression.substr(start, cursor - p_start)); }
#line 243 "scanner.cpp"
yy33:
        ++cursor;
#line 75 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_RIGHT_P, expression.substr(start, cursor - p_start)); }
#line 248 "scanner.cpp"
yy35:
        ++cursor;
#line 76 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_EOF, expression.substr(start, cursor - p_start)); }
#line 253 "scanner.cpp"
yy37:
        yych = (unsigned char)*++cursor;
        goto yy10;
yy38:
        ++cursor;
        yych = (unsigned char)*cursor;
yy39:
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy38;
        default:    goto yy5;
        }
yy40:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'T':
        case 't':    goto yy41;
        default:    goto yy39;
        }
yy41:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy38;
        default:    goto yy42;
        }
yy42:
#line 63 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_NOT, expression.substr(start, cursor - p_start)); }
#line 405 "scanner.cpp"
yy43:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy38;
        default:    goto yy44;
        }
yy44:
#line 62 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_OR, expression.substr(start, cursor - p_start)); }
#line 477 "scanner.cpp"
yy45:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'D':
        case 'd':    goto yy46;
        default:    goto yy39;
        }
yy46:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy38;
        default:    goto yy47;
        }
yy47:
#line 61 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_AND, expression.substr(start, cursor - p_start)); }
#line 556 "scanner.cpp"
yy48:
        ++cursor;
#line 59 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_NOT_EQUAL, expression.substr(start, cursor - p_start)); }
#line 561 "scanner.cpp"
yy50:
        ++cursor;
#line 58 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_EQUAL, expression.substr(start, cursor - p_start)); }
#line 566 "scanner.cpp"
yy52:
        ++cursor;
#line 57 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_GREATER_OR_EQUAL, expression.substr(start, cursor - p_start)); }
#line 571 "scanner.cpp"
yy54:
        ++cursor;
#line 56 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LESS_OR_EQUAL, expression.substr(start, cursor - p_start)); }
#line 576 "scanner.cpp"
yy56:
        ++cursor;
        yych = (unsigned char)*cursor;
yy57:
        switch (yych) {
        case '"':    goto yy60;
        case '\\':    goto yy58;
        default:    goto yy56;
        }
yy58:
        ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '"':
        case '\\':    goto yy56;
        default:    goto yy59;
        }
yy59:
        cursor = marker;
        switch (yyaccept) {
        case 0: 	goto yy8;
        case 1: 	goto yy10;
        }
yy60:
        ++cursor;
#line 52 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_STRING, expression.substr(1 + start, cursor - p_start - 2)); }
#line 604 "scanner.cpp"
yy62:
        yyaccept = 0;
        marker = ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '.':    goto yy64;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy62;
        case 'E':
        case 'e':    goto yy66;
        default:    goto yy8;
        }
yy64:
        yyaccept = 0;
        marker = ++cursor;
        yych = (unsigned char)*cursor;
yy65:
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy64;
        case 'E':
        case 'e':    goto yy66;
        default:    goto yy8;
        }
yy66:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '+':
        case '-':    goto yy67;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy68;
        default:    goto yy59;
        }
yy67:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy68;
        default:    goto yy59;
        }
yy68:
        ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy68;
        default:    goto yy8;
        }
yy70:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'L':
        case 'l':    goto yy71;
        default:    goto yy39;
        }
yy71:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'S':
        case 's':    goto yy72;
        default:    goto yy39;
        }
yy72:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'E':
        case 'e':    goto yy73;
        default:    goto yy39;
        }
yy73:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy38;
        default:    goto yy74;
        }
yy74:
#line 49 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_BOOLEAN, expression.substr(start, cursor - p_start)); }
#line 785 "scanner.cpp"
yy75:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'U':
        case 'u':    goto yy76;
        default:    goto yy39;
        }
yy76:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'E':
        case 'e':    goto yy73;
        default:    goto yy39;
        }
yy77:
        ++cursor;
        yych = (unsigned char)*cursor;
yy78:
        switch (yych) {
        case '\t':
        case ' ':    goto yy77;
        default:    goto yy2;
        }
    }
#line 79 "scanner.re"

}
}
