/* Generated by re2c 0.13.5 on Fri Nov  7 03:28:19 2014 */
#line 1 "scanner.re"
#include "scanner.h"

namespace scanner
{

CToken scan(const std::string& expression, size_t& offset)
{
    std::string::const_pointer marker;
    std::string::const_pointer cursor = expression.c_str() + offset;
    std::string::const_pointer p_start = expression.c_str() + offset;
    size_t start = offset;


#line 17 "scanner.cpp"
    {
        unsigned char yych;
        unsigned int yyaccept = 0;

        yych = (unsigned char)*cursor;
        switch (yych) {
        case 0x00:    goto yy36;
        case '\t':
        case ' ':    goto yy3;
        case '!':    goto yy17;
        case '"':    goto yy9;
        case '%':    goto yy27;
        case '(':    goto yy32;
        case ')':    goto yy34;
        case '*':    goto yy29;
        case '+':    goto yy21;
        case '-':    goto yy23;
        case '/':    goto yy25;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy7;
        case '<':    goto yy11;
        case '=':    goto yy15;
        case '>':    goto yy13;
        case 'A':
        case 'a':    goto yy18;
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy31;
        case 'F':
        case 'f':    goto yy6;
        case 'N':
        case 'n':    goto yy20;
        case 'O':
        case 'o':    goto yy19;
        case 'T':
        case 't':    goto yy4;
        default:    goto yy38;
        }
yy2:
#line 49 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_SPACE, expression.substr(start, cursor - p_start)); }
#line 107 "scanner.cpp"
yy3:
        yych = (unsigned char)*++cursor;
        goto yy79;
yy4:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case 'R':
        case 'r':    goto yy76;
        default:    goto yy40;
        }
yy5:
#line 73 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_IDENTIFIER, expression.substr(start, cursor - p_start)); }
#line 121 "scanner.cpp"
yy6:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'A':
        case 'a':    goto yy71;
        default:    goto yy40;
        }
yy7:
        yyaccept = 0;
        yych = (unsigned char)*(marker = ++cursor);
        switch (yych) {
        case '.':    goto yy65;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy63;
        default:    goto yy66;
        }
yy8:
#line 51 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_FLOAT, expression.substr(start, cursor - p_start)); }
#line 149 "scanner.cpp"
yy9:
        yyaccept = 1;
        yych = (unsigned char)*(marker = ++cursor);
        goto yy58;
yy10:
#line 81 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_ERROR, expression.substr(start, cursor - p_start)); }
#line 157 "scanner.cpp"
yy11:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '=':    goto yy55;
        default:    goto yy12;
        }
yy12:
#line 55 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LESS, expression.substr(start, cursor - p_start)); }
#line 167 "scanner.cpp"
yy13:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '=':    goto yy53;
        default:    goto yy14;
        }
yy14:
#line 56 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_GREATER, expression.substr(start, cursor - p_start)); }
#line 177 "scanner.cpp"
yy15:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '=':    goto yy51;
        default:    goto yy16;
        }
yy16:
#line 78 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_ASSIGN, expression.substr(start, cursor - p_start)); }
#line 187 "scanner.cpp"
yy17:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '=':    goto yy49;
        default:    goto yy10;
        }
yy18:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'N':
        case 'n':    goto yy46;
        default:    goto yy40;
        }
yy19:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'R':
        case 'r':    goto yy44;
        default:    goto yy40;
        }
yy20:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'O':
        case 'o':    goto yy41;
        default:    goto yy40;
        }
yy21:
        ++cursor;
#line 66 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_PLUS, expression.substr(start, cursor - p_start)); }
#line 219 "scanner.cpp"
yy23:
        ++cursor;
#line 67 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_MINUS, expression.substr(start, cursor - p_start)); }
#line 224 "scanner.cpp"
yy25:
        ++cursor;
#line 69 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_DIVIDE, expression.substr(start, cursor - p_start)); }
#line 229 "scanner.cpp"
yy27:
        ++cursor;
#line 70 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_MOD, expression.substr(start, cursor - p_start)); }
#line 234 "scanner.cpp"
yy29:
        ++cursor;
#line 71 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_TIMES, expression.substr(start, cursor - p_start)); }
#line 239 "scanner.cpp"
yy31:
        yych = (unsigned char)*++cursor;
        goto yy40;
yy32:
        ++cursor;
#line 75 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LEFT_P, expression.substr(start, cursor - p_start)); }
#line 247 "scanner.cpp"
yy34:
        ++cursor;
#line 76 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_RIGHT_P, expression.substr(start, cursor - p_start)); }
#line 252 "scanner.cpp"
yy36:
        ++cursor;
#line 80 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_EOF, expression.substr(start, cursor - p_start)); }
#line 257 "scanner.cpp"
yy38:
        yych = (unsigned char)*++cursor;
        goto yy10;
yy39:
        ++cursor;
        yych = (unsigned char)*cursor;
yy40:
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy39;
        default:    goto yy5;
        }
yy41:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'T':
        case 't':    goto yy42;
        default:    goto yy40;
        }
yy42:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy39;
        default:    goto yy43;
        }
yy43:
#line 64 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_NOT, expression.substr(start, cursor - p_start)); }
#line 409 "scanner.cpp"
yy44:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy39;
        default:    goto yy45;
        }
yy45:
#line 63 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_OR, expression.substr(start, cursor - p_start)); }
#line 481 "scanner.cpp"
yy46:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'D':
        case 'd':    goto yy47;
        default:    goto yy40;
        }
yy47:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy39;
        default:    goto yy48;
        }
yy48:
#line 62 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_AND, expression.substr(start, cursor - p_start)); }
#line 560 "scanner.cpp"
yy49:
        ++cursor;
#line 60 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_NOT_EQUAL, expression.substr(start, cursor - p_start)); }
#line 565 "scanner.cpp"
yy51:
        ++cursor;
#line 59 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_EQUAL, expression.substr(start, cursor - p_start)); }
#line 570 "scanner.cpp"
yy53:
        ++cursor;
#line 58 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_GREATER_OR_EQUAL, expression.substr(start, cursor - p_start)); }
#line 575 "scanner.cpp"
yy55:
        ++cursor;
#line 57 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_LESS_OR_EQUAL, expression.substr(start, cursor - p_start)); }
#line 580 "scanner.cpp"
yy57:
        ++cursor;
        yych = (unsigned char)*cursor;
yy58:
        switch (yych) {
        case '"':    goto yy61;
        case '\\':    goto yy59;
        default:    goto yy57;
        }
yy59:
        ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '"':
        case '\\':    goto yy57;
        default:    goto yy60;
        }
yy60:
        cursor = marker;
        switch (yyaccept) {
        case 0: 	goto yy8;
        case 1: 	goto yy10;
        }
yy61:
        ++cursor;
#line 53 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_STRING, expression.substr(1 + start, cursor - p_start - 2)); }
#line 608 "scanner.cpp"
yy63:
        yyaccept = 0;
        marker = ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '.':    goto yy65;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy63;
        case 'E':
        case 'e':    goto yy67;
        default:    goto yy8;
        }
yy65:
        yyaccept = 0;
        marker = ++cursor;
        yych = (unsigned char)*cursor;
yy66:
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy65;
        case 'E':
        case 'e':    goto yy67;
        default:    goto yy8;
        }
yy67:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '+':
        case '-':    goto yy68;
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy69;
        default:    goto yy60;
        }
yy68:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy69;
        default:    goto yy60;
        }
yy69:
        ++cursor;
        yych = (unsigned char)*cursor;
        switch (yych) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':    goto yy69;
        default:    goto yy8;
        }
yy71:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'L':
        case 'l':    goto yy72;
        default:    goto yy40;
        }
yy72:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'S':
        case 's':    goto yy73;
        default:    goto yy40;
        }
yy73:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'E':
        case 'e':    goto yy74;
        default:    goto yy40;
        }
yy74:
        ++cursor;
        switch ((yych = (unsigned char)*cursor)) {
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        case 'A':
        case 'B':
        case 'C':
        case 'D':
        case 'E':
        case 'F':
        case 'G':
        case 'H':
        case 'I':
        case 'J':
        case 'K':
        case 'L':
        case 'M':
        case 'N':
        case 'O':
        case 'P':
        case 'Q':
        case 'R':
        case 'S':
        case 'T':
        case 'U':
        case 'V':
        case 'W':
        case 'X':
        case 'Y':
        case 'Z':
        case '_':
        case 'a':
        case 'b':
        case 'c':
        case 'd':
        case 'e':
        case 'f':
        case 'g':
        case 'h':
        case 'i':
        case 'j':
        case 'k':
        case 'l':
        case 'm':
        case 'n':
        case 'o':
        case 'p':
        case 'q':
        case 'r':
        case 's':
        case 't':
        case 'u':
        case 'v':
        case 'w':
        case 'x':
        case 'y':
        case 'z':    goto yy39;
        default:    goto yy75;
        }
yy75:
#line 50 "scanner.re"
        { offset += cursor - p_start; return CToken(ET_BOOLEAN, expression.substr(start, cursor - p_start)); }
#line 789 "scanner.cpp"
yy76:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'U':
        case 'u':    goto yy77;
        default:    goto yy40;
        }
yy77:
        yych = (unsigned char)*++cursor;
        switch (yych) {
        case 'E':
        case 'e':    goto yy74;
        default:    goto yy40;
        }
yy78:
        ++cursor;
        yych = (unsigned char)*cursor;
yy79:
        switch (yych) {
        case '\t':
        case ' ':    goto yy78;
        default:    goto yy2;
        }
    }
#line 83 "scanner.re"

}
}
