#define ET_WHERE_ASSIGN                           1
#define ET_WHERE_AND                              2
#define ET_WHERE_OR                               3
#define ET_WHERE_IS                               4
#define ET_WHERE_IS_NOT                           5
#define ET_WHERE_NOT                              6
#define ET_WHERE_LESS                             7
#define ET_WHERE_LESS_OR_EQUAL                    8
#define ET_WHERE_GREATER                          9
#define ET_WHERE_GREATER_OR_EQUAL                10
#define ET_WHERE_EQUAL                           11
#define ET_WHERE_NOT_EQUAL                       12
#define ET_WHERE_PLUS                            13
#define ET_WHERE_MINUS                           14
#define ET_WHERE_LIKE                            15
#define ET_WHERE_TIMES                           16
#define ET_WHERE_DIVIDE                          17
#define ET_WHERE_MOD                             18
#define ET_WHERE_UMINUS                          19
#define ET_WHERE_DOT                             20
#define ET_WHERE_IDENTIFIER                      21
#define ET_WHERE_FIELD                           22
#define ET_WHERE_INTEGER                         23
#define ET_WHERE_FLOAT                           24
#define ET_WHERE_BOOLEAN                         25
#define ET_WHERE_STRING                          26
#define ET_WHERE_NULL                            27
#define ET_WHERE_LEFT_P                          28
#define ET_WHERE_RIGHT_P                         29
